spring:
  profiles:
    active: local
  application:
    name: "basic"
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true
