spring:
  application:
    name: "basic"
  profiles:
    active: "dev"
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
        # IN?? ???? ??
        default_batch_fetch_size: 100
  datasource:
    basic:
      pool-name: default-hikari-pool
      jdbc-url: jdbc:mysql://${MYSQL_HOST:localhost:3306/basic}?serverTimezone=UTC&characterEncoding=UTF-8&rewriteBatchedStatements=true
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASSWORD:hhhh}
      maximum-pool-size: 10
      driver-class-name: com.mysql.cj.jdbc.Driver
      read-only: false
      validation-timeout: 500
      connection-timeout: 30000
      keepalive-time: 0
      auto-commit: true

